variables:
  GLOBAL_C11: "true" # Enable C++11 everywhere by default
  # If package name is "ros-kinetic-actionlib" it becomes "actionlib" (remove the prefix)
  ROS_PACKAGES_TO_INSTALL: "dynamic-reconfigure"

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash
 - apt-get install --assume-yes libqt4-dev > /dev/null 

cache:
  paths:
    - ccache/

kinetic-catkin_build:
  image: ros:kinetic-ros-core
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
