variables:
  GLOBAL_C11: "true" # Enable C++11 everywhere by default
  # If package name is "ros-kinetic-actionlib" it becomes "actionlib" (remove the prefix)
  ROS_PACKAGES_TO_INSTALL: "dynamic_reconfigure nodelet" # Here the package is useless, it is just for demonstration

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash
 - sudo apt-get install libqt4-dev

cache:
  paths:
    - ccache/

kinetic-catkin_build:
  image: ros:kinetic-ros-core
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
