set(_CATKIN_CURRENT_PACKAGE "parsian_ai")
set(parsian_ai_VERSION "0.0.0")
set(parsian_ai_MAINTAINER "Mohammad Mahdi Rahimi <mohammadmahdi76@gmail.com>")
set(parsian_ai_PACKAGE_FORMAT "1")
set(parsian_ai_BUILD_DEPENDS "dynamic_reconfigure" "parsian_msgs" "parsian_util" "roscpp" "rospy" "nodelet")
set(parsian_ai_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "parsian_msgs" "parsian_util" "roscpp" "rospy" "nodelet")
set(parsian_ai_BUILDTOOL_DEPENDS "catkin")
set(parsian_ai_BUILDTOOL_EXPORT_DEPENDS )
set(parsian_ai_EXEC_DEPENDS "dynamic_reconfigure" "parsian_msgs" "parsian_util" "roscpp" "rospy" "nodelet")
set(parsian_ai_RUN_DEPENDS "dynamic_reconfigure" "parsian_msgs" "parsian_util" "roscpp" "rospy" "nodelet")
set(parsian_ai_TEST_DEPENDS )
set(parsian_ai_DOC_DEPENDS )
set(parsian_ai_DEPRECATED "")