set(parsian_ai_SETUP_PY_VERSION "0.0.0")
set(parsian_ai_SETUP_PY_SCRIPTS "")
set(parsian_ai_SETUP_PY_PACKAGES "parsian_ai")
set(parsian_ai_SETUP_PY_PACKAGE_DIRS "src/parsian_ai")
set(parsian_ai_SETUP_PY_MODULES "")
set(parsian_ai_SETUP_PY_MODULE_DIRS "")